#!/usr/bin/env python3
"""Generate docs/MIGRATION-MAP.md and the parity table from evidence/*.

Reads:
  evidence/migration-map.json   (authoritative src -> rust mapping)
  evidence/status/<slice>.json  (per-file worker reports)

Writes:
  docs/MIGRATION-MAP.md
  evidence/parity-table.json

Run from the repo root:  python scripts/gen-migration-map.py
"""
from __future__ import annotations

import json
import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
EVIDENCE = ROOT / "evidence"


def load_status() -> dict[str, dict]:
    """Map src path -> the worker's report for that file."""
    by_src: dict[str, dict] = {}
    status_dir = EVIDENCE / "status"
    if not status_dir.is_dir():
        return by_src
    for path in sorted(status_dir.glob("*.json")):
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            continue
        slice_name = data.get("slice", path.stem)
        for entry in data.get("files", []) or []:
            src = entry.get("src")
            if not src:
                continue
            record = dict(entry)
            record["slice"] = slice_name
            record["build"] = data.get("build", "")
            record["tests"] = data.get("tests", "")
            record["blocked_on"] = data.get("blocked_on", "")
            # Keep the most pessimistic status if two reports exist for one file.
            previous = by_src.get(src)
            if previous is None or _rank(record) >= _rank(previous):
                by_src[src] = record
    return by_src


_RANK = {"blocked": 0, "partial": 1, "ported": 2}


def _rank(record: dict) -> int:
    return _RANK.get(str(record.get("status", "")), -1)


def rust_line_count(rel: str) -> int:
    path = ROOT / rel
    if not path.exists():
        return 0
    try:
        return len(path.read_text(encoding="utf-8", errors="replace").splitlines())
    except OSError:
        return 0


def main() -> int:
    mapping = json.loads((EVIDENCE / "migration-map.json").read_text(encoding="utf-8"))
    status = load_status()

    rows = []
    for item in mapping:
        src = item["src"]
        rust = item["rust"]
        report = status.get(src, {})
        written = rust_line_count(rust)
        reported = report.get("status")
        if reported in ("ported", "partial", "blocked"):
            state = reported
        elif written == 0:
            state = "not started"
        else:
            state = "written (unreported)"
        rows.append(
            {
                "src": src,
                "rust": rust,
                "crate": item["crate"],
                "ts_loc": item["loc"],
                "rust_loc": written,
                "status": state,
                "slice": report.get("slice", ""),
                "functions_mapped": report.get("functions_mapped"),
                "notes": report.get("notes", ""),
                "verified": "yes" if state == "ported" and report.get("build", "").endswith("ok") else "no",
            }
        )

    (EVIDENCE / "parity-table.json").write_text(json.dumps(rows, indent=1), encoding="utf-8")

    counts: dict[str, int] = {}
    for row in rows:
        counts[row["status"]] = counts.get(row["status"], 0) + 1

    lines = [
        "# MIGRATION-MAP",
        "",
        "Generated by `python scripts/gen-migration-map.py` from `evidence/migration-map.json`",
        "and `evidence/status/*.json`. Do not edit by hand.",
        "",
        "The mapping is 1:1: `packages/<pkg>/src/<a>/<b>.ts` -> `crates/<crate>/src/<a>/<b>.rs`",
        "(kebab-case becomes snake_case, `index.ts` becomes `mod.rs`).",
        "",
        "## Status totals",
        "",
        "| Status | Files |",
        "|---|---|",
    ]
    for state in sorted(counts):
        lines.append(f"| {state} | {counts[state]} |")
    lines += ["| **total** | **%d** |" % len(rows), ""]

    lines += [
        "## File mapping",
        "",
        "| Original TypeScript | Rust port | Crate | TS LOC | Rust LOC | Status | Behaviour verified |",
        "|---|---|---|---|---|---|---|",
    ]
    for row in rows:
        lines.append(
            "| `{src}` | `{rust}` | {crate} | {ts_loc} | {rust_loc} | {status} | {verified} |".format(**row)
        )

    lines += ["", "## Slice reports", ""]
    for path in sorted((EVIDENCE / "status").glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        lines.append(f"### {data.get('slice', path.stem)}")
        lines.append("")
        lines.append(f"- build: `{data.get('build', 'not run')}`")
        lines.append(f"- tests: `{data.get('tests', 'not run')}`")
        blocked = data.get("blocked_on") or "none"
        lines.append(f"- blocked_on: {blocked}")
        summary = data.get("honest_summary")
        if summary:
            lines.append(f"- honest summary: {summary}")
        lines.append("")

    (ROOT / "docs" / "MIGRATION-MAP.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote docs/MIGRATION-MAP.md ({len(rows)} files)")
    print("status totals:", counts)
    return 0


if __name__ == "__main__":
    sys.exit(main())
